name: uploaddocs
on:
  push:
    branches:
      - develop
      
  workflow_dispatch: 
  
jobs:
  build:
    name: build docs 
    runs-on: ubuntu-latest
    steps:
      - name: Build Web App
        run: |
          echo "Build Web App"
          sleep 10s
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: doriancrutcher
          repo: docs2
          github_token: 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
          workflow_file_name: typedocs.yml
          ref: deploy
      - name: Deploy Web App
        run: |
          echo "UpdateTypeDocs"
          sleep 10s
