name: uploaddocs
on:
  push:
    branches:
      - develop
      
  workflow_dispatch: 
  
jobs:
  build:
    name: build docs 
    runs-on: ubuntu-latest
    steps:
      - name: CREATE TYPE DOCS
        run: |
          echo "make typedocs
          sleep 10s
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: doriancrutcher
          repo: docs2
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
          workflow_file_name: typedocs.yml
          trigger_workflow: true
          
