name: Dispatch repo-b-update event

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch event
        uses: doriancrutcher/docs2
        with:
          token: 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
          event-type: repo-b-update
